controllers/MainController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\Response;
use yii\helpers\Url;

use app\models\LoginForm;
use app\models\Portfolio;
use app\models\ProductManuf;
use app\models\ProductRootcat;
use app\components\ProductsManager;

class MainController extends Controller
{
    public $defaultAction = 'page';

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionPage($view='index')
    {
        if ($view=='index') {
            $portfolios = Portfolio::find()->asArray()->all();
            for ($i=0;$i<count($portfolios);$i++) {
                $photoPath = Yii::getAlias('@uploadPath')."/portfolio/photo/".$portfolios[$i]['photo'];
                $photoParamsMini =  [
                    'thumbnail' => [
                        'width' => 320,
                        'height' => 213,
                    ],
                    'placeholder' => [
                        'width' => 320,
                        'height' => 213
                    ]
                ];
                $photoParamsBig =  [
                    'thumbnail' => [
                        'width' => 450,
                        'height' => 300,
                    ],
                    'placeholder' => [
                        'width' => 450,
                        'height' => 300
                    ]
                ];
                $portfolios[$i]['photo-mini'] = '/web/'.Yii::$app->thumbnail->url($photoPath, $photoParamsMini);
                $portfolios[$i]['photo-big'] = '/web/'.Yii::$app->thumbnail->url($photoPath, $photoParamsBig);
            }
            return $this->render($view,['portfolios'=>$portfolios]);
        }

        return $this->render($view);
    }

    public function actionNapravleniya($catagoryView="",$subCatagoryView="")
    {   
        if ($catagoryView!="komplectaciya") {
            $view = 'napravleniya/'.$catagoryView;
            $this->layout = "napravleniyaLayout"; 
        }
        else {
            if ($subCatagoryView!=null) {


            $view = 'napravleniya/komplectaciya-category';
            $this->layout = "komplectaciyaLayout";

            $productRootcatId = ProductRootcat::getIdByViewName($subCatagoryView);
            $productSubcats = ProductsManager::getSubcatsWithProducts($productRootcatId); 

            switch ($subCatagoryView) {
                case 'izmeritelnoe-oborudivanie':
                    $this->view->params['komplectaciya-category-title'] = "Измерительное оборудование";
                    break;  
                case 'injenernoe-oborudivanie':
                    $this->view->params['komplectaciya-category-title'] = "Инженерное обрудование";
                    break;
                case 'oborudivanie-dly-avtomatizacii':
                    $this->view->params['komplectaciya-category-title'] = "Обрудование для автоматизации";
                    break;              
            }

            $this->view->params['subCatagoryView'] = $subCatagoryView;
            $this->view->params['productSubcats'] = $productSubcats;           
            }
            else {
                $allProductSubcats = [];
                $allProductSubcats[0] = ProductsManager::getSubcats(0); 
                $allProductSubcats[1] = ProductsManager::getSubcats(1);
                $allProductSubcats[2] = ProductsManager::getSubcats(2);

                $this->view->params['allProductSubcats'] = $allProductSubcats;
                $this->layout = "napravleniyaLayout"; 
                $view = 'napravleniya/komplectaciya';
            }
        }
        $this->view->params['catagoryView'] = $catagoryView; 
        return $this->render($view);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['admin']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return Yii::$app->response->redirect(['admin/model/list','name'=>'portfolio']);
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

views/layouts/base.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */
use app\assets\CommonAsset;
use yii\helpers\Url;

CommonAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
    <meta name="viewport" content="width=1300">
    <title>АЭС</title>
   
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
    <div class="header-top-wr">
        <div class="header-top p-line">
            <a href="tel:+73517313210" class="header-top_phone">+7 (351) 731-32-10</a>
            <a href="mailto:mail@aeschel.ru" class="header-top_email">mail@aeschel.ru</a>
            <div class="header-top_call-btn" onclick="window.orderPopup.show()">ОСТАВИТЬ ЗАЯВКУ</div>
        </div>
    </div>

    <div class="header-wrap">
        <img class="heade_bg1" src="/img/soti-mini.png">
        <img class="heade_bg2" src="/img/soti-mini.png">
        <div class="header p-line">
            <div class="header_logo">
                <a href="/">
                    <img src="/img/logo-header.png" class="header_logo-img">
                </a>
            </div>  

            <div class="header_menu-wr">
                <ul class="header_menu-ul">
                    <li class="header_menu-li">
                        <a href="/#about" class="header_menu-a">О КОМПАНИИ</a>
                    </li>
                    <li class="header_menu-li">
                        <a href="/#works" class="header_menu-a">ВЫПОЛНЕННЫЕ ПРОЕКТЫ</a>
                    </li>
                    <!-- <li class="header_menu-li">
                        <a href="#" class="header_menu-a">ЛИЦЕНЗИИ</a>
                    </li> -->
                    <li class="header_menu-li">
                        <a href="<?php echo Url::toRoute(['main/page', 'view' => 'contacti']); ?>" class="header_menu-a">КОНТАКТЫ</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <?= $content ?>

    <div class="main-form">
        <div class="p-line">
            <form class="main-form_form">
                <div class="main-form_title">Напишите нам</div>
                <div class="main-form_subtitle">и мы обязательно с Вами свяжемся</div> 
                <div class="main-form_inputs-line">
                    <div class="main-form_inp-wrap formWrapName">
                        <input class="main-form_inp-val formInput" type="text" placeholder="Ваше имя">
                        <div class="main-form_inp-req">обязательное поле</div>
                    </div>
                    <div class="main-form_inp-wrap formWrapPhone">
                        <input class="main-form_inp-val formInput" type="text" placeholder="Ваш телефон">
                        <div class="main-form_inp-req">обязательное поле</div>
                    </div>
                    <div class="main-form_inp-wrap formWrapEmail">
                        <input class="main-form_inp-val formInput" type="email" placeholder="Ваш e-mail">
                        <div class="main-form_inp-req">обязательное поле</div>
                    </div>
                </div>
                <div class="main-form_text-wrap formWrapText">
                    <textarea class="main-form_text-val formInput" placeholder="Сообщение"></textarea>
                    <div class="main-form_inp-req">обязательное поле</div>
                </div>
                
                <div class="main-form_bottom formWrapConfirm">
                    <div class="main-form_confirmCehck-wrap ">
                        <input type="checkbox" id="main-form_confirmCehck" class="main-form_confirmCehck formInput">
                        <label for="main-form_confirmCehck" class="main-form_confirmCehck-label">Даю согласие на обработку <a href="#" class="main-form_confirmCehck-link  formShowFullConfirm">пересональных данных</a></label>
                        <div class="main-form_inp-req">вы не дали согласия на обработку персональных данных</div>
                    </div>
                    <div class="main-form_full-confirm formFullConfirm">
                        <div class="main-form_full-confirm-close formCloseFullConfirm"></div>
                        <input type="checkbox" id="main-form_full-confirm-check" class="main-form_full-confirm-check formFullConfirmCheck">
                        <label for="main-form_full-confirm-check" class="main-form_full-confirm-label">Я выражаю свое согласие на осуществление обработки (сбора, систематизации, накопления, хранения, уточнения, обновления, изменения, использования, обезличивания, блокирования и уничтожения) в том числе автоматизированной, моих персональных данных, указанных на сайте, в соответствии с требованиями Федерального закона от 27.07.2006 года № 152-ФЗ «О персональных данных».</label>
                    </div>
                    <div class="main-form_send-btn formSendBtn">отправить</div>
                </div>
            </form>
            <div class="main-form_sending">
                <img src="/img/loading.gif" class="main-form_sending-img">
            </div>
            <div class="main-form_success">
                <div class="main-form_success-title">Сообщение отправлено!</div>
                <div class="main-form_success-text">Мы свяжемся с вами в ближайшее время.</div>
            </div>
            <div class="main-form_fail">
                <div class="main-form_fail-title">Произошла ошибка. Сообщение не доставлено.</div>
                <div class="main-form_fail-text">В случае повторения ошибки, свяжитесь с нами по телефону, указанному в контактах.</div>
            </div>  
        </div>
    </div>

    <div class="footer p-line">
        <div class="footer_clm1">
            <a href="<?php echo Url::toRoute(['napravleniya', 'catagoryView' => 'proektirovanie']); ?>" class="f-menu_title">НАПРАВЛЕНИЯ</a>
            <a href="<?php echo Url::toRoute(['napravleniya', 'catagoryView' => 'proektirovanie']); ?>" class="f-menu_item">Проектирование</a>
            <a href="<?php echo Url::toRoute(['napravleniya', 'catagoryView' => 'komplectaciya']); ?>" class="f-menu_item">Комплектация оборудованием</a>
            <a href="<?php echo Url::toRoute(['napravleniya', 'catagoryView' => 'stroy-montaj']); ?>" class="f-menu_item">Строительно-монтажные, пусконаладочные работы</a>
            <a href="<?php echo Url::toRoute(['napravleniya', 'catagoryView' => 'garantiynoe-i-servisnoe']); ?>" class="f-menu_item">Гарантийное и сервисное обслуживани</a>
        </div>
        <div class="footer_clm2">
            <a href="#works" class="f-menu_title">ВЫПОЛНЕННЫЕ РАБОТЫ</a>
            <!--  <a href="#" class="f-menu_title">ЛИЦЕНЗИИ</a> -->
            <a href="<?php echo Url::toRoute(['main/page', 'view' => 'contacti']); ?>" class="f-menu_title">КОНТАКТЫ</a>
            <p class="footer_copyright">© «Агентство энергетического сервиса»</p>
            <p class="footer_design">
                Дизайн сайта
                <a class="footer_design-a">Студия Евгении Гайда</a>
            </p>
        </div>
        <div class="footer_clm3">
            <img class="footer_logo" src="/img/logo-footer.png">
            <a href="tel:+73517313210" class="footer_phone">
                <span class="footer_phone-pre">+7 (351)</span>
                731-32-10
            </a>
            <a href="mailto:mail@aeschel.ru" class="footer_email">mail@aeschel.ru</a>
            <div class="footer_call-btn" onclick="window.orderPopup.show()">ЗАКАЗАТЬ ЗВОНОК</div>
            
        </div>
    </div>

    <!--всплывающее окно заказать звононк -->
    <?php echo $this->render('@app/views/layouts/components/order-popup',[]); ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/komplectaciyaLayout.php
<?php 
use app\assets\EquipmentsAsset;
EquipmentsAsset::register($this); 

?>

<?php $this->beginContent('@app/views/layouts/napravleniyaLayout.php'); ?>

<div class="text-page_title text-page_title__komplect">КОМПЛЕКТАЦИЯ ОБОРУДОВАНИЕМ</div>

<?php if (YII_ENV_DEV): ?>
	<div class="text-page_text">
		<?php echo $content; ?>
	</div>
	<?php echo $this->render('@app/views/main/napravleniya/components/komplectaciya-order-popup',[]); ?>
<?php else: ?>
	<div class="text-page_catalog-load">
		Каталог обрудования обновляется.
	</div>
<?php endif; ?>
		
<?php $this->endContent(); ?>

views/layouts/napravleniyaLayout.php
<?php
use app\assets\NapravleniyaAsset;
use yii\helpers\Url;

NapravleniyaAsset::register($this);
?>

<?php $this->beginContent('@app/views/layouts/base.php'); ?>
<div class="text-page">
	<div class="text-page_menu">
		<?php echo $this->render('@app/views/main/napravleniya/components/menu',['activeItem'=>$this->params['catagoryView'],'activeSubItem'=>$this->params['subCatagoryView']]); ?>
	</div>	
	<div class="text-page_content">
		<?php echo $content; ?>		
	</div>
	<div class="text-page_bottom"></div>
</div>
<?php $this->endContent(); ?>